-- Create database if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'DIAMOND_PROJECT')
BEGIN
    CREATE DATABASE DIAMOND_PROJECT;
END
GO

-- Use the DIAMOND_PROJECT database
USE DIAMOND_PROJECT
GO

-- Drop existing tables if they exist
IF OBJECT_ID('ORDERITEM', 'U') IS NOT NULL
    DROP TABLE ORDERITEM;

IF OBJECT_ID('ORDERS', 'U') IS NOT NULL
    DROP TABLE ORDERS;

IF OBJECT_ID('DIAMONDPRODUCT', 'U') IS NOT NULL
    DROP TABLE DIAMONDPRODUCT;

IF OBJECT_ID('CUSTOMER', 'U') IS NOT NULL
    DROP TABLE CUSTOMER;
GO

-- Create the CUSTOMER table
CREATE TABLE CUSTOMER (
  CustomerID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  Username VARCHAR(50),
  Password VARCHAR(100),
  RegistrationDate DATETIME
);

-- Create the DIAMOND table
CREATE TABLE DIAMONDPRODUCT (
  ProductID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  ProductType VARCHAR(50), --Ring, Pendant, Bracelet
  Name VARCHAR(100),
  Price MONEY,
  ImageURL VARCHAR(255),
  Shape VARCHAR(20),
  CaratWeight VARCHAR(20),
  Color VARCHAR(20),
  Clarity VARCHAR(20),
  Cut VARCHAR(20),
  ProductStatus VARCHAR(50) DEFAULT 'Available' --Available, Ordered, Unavailable
);

-- Create the ORDERS table
CREATE TABLE ORDERS (
  OrderID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  CustomerID UNIQUEIDENTIFIER,
  OrderDate DATETIME,
  TotalAmount MONEY,
  OrderStatus VARCHAR(50) DEFAULT 'Ongoing', --Ongoing, Completed, Cancelled
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

-- Create the ORDERITEM table
CREATE TABLE ORDERITEM (
  OrderItemID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  OrderID UNIQUEIDENTIFIER,
  DProductID UNIQUEIDENTIFIER NULL,
  Price MONEY,
  ProductType VARCHAR(500),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
  CONSTRAINT FK_Orderitem_Diamond FOREIGN KEY (DProductID) REFERENCES DIAMONDPRODUCT(ProductID),
);